### ISSUE TITLE
[Bug] Not using GPU, %100 CPU

### ISSUE THREAD

**Issue by CptJackieSparrow** [lkwq007/stablediffusion-infinity#133]
The process is extremely slow.

I've expected to see GPU usage on the task manager, but it's %100 CPU.
I have my Founders Edition RTX 3080 Ti and i9 12900K

**Comment by VRamxn** [comment]
https://github.com/lkwq007/stablediffusion-infinity/issues/123#issuecomment-1294736390

**Comment by CptJackieSparrow** [comment]
I don’t even have the file 'libiomp5md.dll' from within envs\sd-inf\Library\bin\

guess pytorch is not utilizing GPU, can’t change the priority on CPU

**Comment by mrfood0** [comment]
Try to pursue the other solution, but I remember having tons of issues with it, and this guy's auto installer bat made everything work for me.
https://youtu.be/mjmGuSdumEE
I think he has a specific installation of pytorch that has GPU support in his installer.

**Comment by Bill4321** [comment]
> I don’t even have the file 'libiomp5md.dll' from within envs\sd-inf\Library\bin\
> 
> guess pytorch is not utilizing GPU, can’t change the priority on CPU

That stopped working. Try deleting the environment and installing using these commands..

conda create -n sd-inf python=3.10
conda activate sd-inf
conda install -c pytorch pytorch=1.12.0
conda install torchvision torchaudio cudatoolkit=11.3 -c pytorch
conda install scipy scikit-image
conda install -c conda-forge diffusers transformers ftfy
pip install opencv-python
pip install gradio==3.6
pip install pytorch-lightning==1.7.7 einops==0.4.1 omegaconf==2.2.3
pip install timm

It worked for me so hopefully will work for you :-)

**Comment by asukii314** [comment]
This worked for me when the official windows install instructions didn't! Thanks so much.

**Comment by Bill4321** [comment]
That's great! I'm pleased that you have it working :-)
