### ISSUE TITLE
Different results on different platform (resizing)

### ISSUE THREAD

**Issue by badcode6** [lkwq007/stablediffusion-infinity#26]
on google colab the image that results from outpainting looks totally normal, but when running the local Windows notebook everything gets messed up.

The only difference between the two environments is google Colab has "Resize SD Input to 512x512" while my windows machine does not. Resizing to 512 causes out of memory error:
```
RuntimeError: CUDA out of memory. Tried to allocate 512.00 MiB (GPU 0; 4.00 GiB total capacity; 2.65 GiB already allocated; 0 bytes free; 3.19 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

This is what it looks like on my local machine. Steps = 50, guidance = 7.5, strength = 0.75, edge pad, resize disabled:
![image](https://user-images.githubusercontent.com/70351049/192910598-b7683a8c-0454-41e5-b4fc-a350ab41765b.png)

Google Colab, same settings as above but with resize enabled:
![image](https://user-images.githubusercontent.com/70351049/192911093-acd9d7b2-834e-4f80-95f7-b4ab7bbdcfad.png)

Is there a way to either use less memory when resizing or get a better outpaint by changing the rest of the settings to accommodate? I am willing to wait a long time to get a better result, I am in no rush.

**Comment by lkwq007** [comment]
Perhaps you can add `inpaint.enable_attention_slicing()` in the `setup StableDiffusionInpaintPipeline` section to reduce vRAM usage

https://github.com/huggingface/diffusers/pull/366

**Comment by badcode6** [comment]
> inpaint.enable_attention_slicing()

Worked like a charm. Thank you
